########################################################################################################################
# GLOBAL
########################################################################################################################

## @section Global parameters
global:

  ## @param global.annotations Define global annotations
  annotations: {}

  cluster:

    istio:
      ## @param global.cluster.istio.enabled Enable Istio Service mesh
      enabled: false

    pdb:
      ## @param global.cluster.pdb.enabled Enable PDB
      enabled: false

    storage:

      data:
        ## @param global.cluster.storage.data.permission Enable global custom data storage permissions
        permission: false
        ## @param global.cluster.storage.data.spec Set data storage spec
        spec: {}

  ## @param global.debug Enable global debugging
  debug: false

  image:
    ## @param global.image.pullPolicy Set global image pullPolicy
    pullPolicy: Always
    ## @param global.image.pullSecrets Set global image pullSecrets
    pullSecrets: []
    ## @param global.image.registry Set global image container registry
    registry: ${docker.registry}
    ## @param global.image.repository Set global image container repository
    repository: ${docker.repository}
    ## @param global.image.common Set global image container common
    common: ${docker.common}

  metrics:
    scrape:
      ## @param global.metrics.scrape.interval Set prometheus scrape interval
      interval: 60s
      ## @param global.metrics.scrape.timeout Set prometheus scrape timeout
      timeout: 60s
    servicemonitor:
      ## @param global.metrics.servicemonitor.enabled Enable metrics service monitor
      enabled: false

  ## @param global.security Set global security parameters
  security: {}

########################################################################################################################
# LOCAL
########################################################################################################################

## @section Local parameters
## @param nameOverride Override name
nameOverride: edusharing-repository-search-solr

image:
  ## @param image.name Set image name
  name: ${docker.edu_sharing.community.common.alfresco.search.service.name}
  ## @param image.tag Set image tag
  tag: "${docker.edu_sharing.community.common.alfresco.search.service.tag}"

########################################################################################################################

## @param replicaCount Define amount of parallel replicas to run
replicaCount: 1

########################################################################################################################

service:

  port:
    ## @param service.port.api Set port for service API
    api: 8080
    ## @param service.port.metrics Set port for metrics
    metrics: 9090

########################################################################################################################

config:

  jvm:
    ## @param config.jvm.opts Set JVM options
    opts: >-
      -XX:+UseG1GC 
      -XX:+PerfDisableSharedMem 
      -XX:+ParallelRefProcEnabled 
      -XX:MaxGCPauseMillis=250 
      -XX:+AlwaysPreTouch 
      -XX:+ExplicitGCInvokesConcurrent
    ram:
      ## @param config.jvm.ram.minPercentage Set minimum memory in percentages
      minPercentage: "75.0"
      ## @param config.jvm.ram.maxPercentage Set maximum memory in percentages
      maxPercentage: "75.0"

  metrics:
    ## @param config.metrics.enabled Enable metrics
    enabled: true
    ## @param config.metrics.relabelings Relable metrics
    relabelings: []

  override:
    application:
      ## @param config.override.application.common Override the application's common
      common: ""
    logging:
      ## @param config.override.logging.application Override logging's application
      application: ""

  repository:
    ## @param config.repository.host Set host of repository
    host: edusharing-repository-service
    ## @param config.repository.port Set port of repository
    port: 8080

########################################################################################################################

multistage:

  ## @param multistage.enabled Enable multistage
  enabled: false

  ## @param multistage.current Set multistage's current
  current: ""

  ## @param multistage.stages Define stages of multistage
  # example:
  #  stages:
  #    - name: blue
  #      spec:
  #        config:
  #          override:
  #            application:
  #              common: ""
  #    - name: green
  #      spec:
  #        config:
  #          override:
  #            application:
  #              common: ""
  stages: []

########################################################################################################################

## @param debug Enable debugging
debug: false

########################################################################################################################

## @param nodeAffinity Set node affinity
nodeAffinity: {}
## @param podAntiAffinity Set pod antiaffinity
podAntiAffinity: "soft"

## @param tolerations Set tolerations
tolerations: []

########################################################################################################################

persistence:

  data:

    spec:
      ## @param persistence.data.spec.accessModes Set access modes for persistent data
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          ## @param persistence.data.spec.resources.requests.storage Set storage request for persistent data
          storage: 5Gi

########################################################################################################################

## @param podAnnotations Set custom pod annotations
podAnnotations: {}

podSecurityContext:

  ## @param podSecurityContext.fsGroup Set fs group for access
  fsGroup: 1000
  ## @param podSecurityContext.fsGroupChangePolicy Set change policy for fs group
  fsGroupChangePolicy: OnRootMismatch

securityContext:

  ## @param securityContext.allowPrivilegeEscalation Allow privilege escalation
  allowPrivilegeEscalation: false
  capabilities:
    ## @param securityContext.capabilities.drop Set drop capabilities
    drop:
    - ALL
  ## @param securityContext.runAsUser Define user to run under
  runAsUser: 1000

########################################################################################################################

## @param terminationGracePeriod Define grace period for termination
terminationGracePeriod: 120

startupProbe:
  ## @param startupProbe.failureThreshold Failure threshold for startupProbe
  failureThreshold: 30
  ## @param startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  initialDelaySeconds: 0
  ## @param startupProbe.periodSeconds Period seconds for startupProbe
  periodSeconds: 20
  ## @param startupProbe.successThreshold Success threshold for startupProbe
  successThreshold: 1
  ## @param startupProbe.timeoutSeconds Timeout seconds for startupProbe
  timeoutSeconds: 10

livenessProbe:
  ## @param livenessProbe.failureThreshold Failure threshold for livenessProbe
  failureThreshold: 3
  ## @param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  initialDelaySeconds: 30
  ## @param livenessProbe.periodSeconds Period seconds for livenessProbe
  periodSeconds: 30
  ## @param livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  timeoutSeconds: 10

readinessProbe:
  ## @param readinessProbe.failureThreshold Failure threshold for readinessProbe
  failureThreshold: 1
  ## @param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  initialDelaySeconds: 10
  ## @param readinessProbe.periodSeconds Period seconds for readinessProbe
  periodSeconds: 10
  ## @param readinessProbe.successThreshold Set threshold for success on readiness probe
  successThreshold: 1
  ## @param readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  timeoutSeconds: 10

########################################################################################################################

resources:

  limits:
    ## @param resources.limits.cpu Set CPU limit on resources
    cpu: 1000m
    ## @param resources.limits.memory Set memory limit on resources
    memory: 4Gi
  requests:
    ## @param resources.requests.cpu Set CPU for requests on resources
    cpu: 1000m
    ## @param resources.requests.memory Set memory for requests on resources
    memory: 4Gi

########################################################################################################################

init:

  permission:

    image:
      ## @param init.permission.image.name Set init container image name
      name: ${docker.edu_sharing.community.common.minideb.name}
      ## @param init.permission.image.tag Set init container image tag
      tag: "${docker.edu_sharing.community.common.minideb.tag}"

    ## @param init.permission.startupProbe Optional specs for startupProbe
    startupProbe:

    ## @param init.permission.livenessProbe Optional specs for livenessProbe
    livenessProbe:

    ## @param init.permission.readinessProbe Optional specs for readinessProbe
    readinessProbe:

    resources:

      limits:
        ## @param init.permission.resources.limits.cpu Set init container CPU limit on resources
        cpu: 125m
        ## @param init.permission.resources.limits.memory Set init container memory limit on resources
        memory: 512Mi
      requests:
        ## @param init.permission.resources.requests.cpu Set init container CPU for requests on resources
        cpu: 125m
        ## @param init.permission.resources.requests.memory Set init container memory for requests on resources
        memory: 512Mi

    securityContext:

      ## @param init.permission.securityContext.runAsUser Set user to run init container under
      runAsUser: 0

########################################################################################################################
